import React, {useState, useContext} from 'react';
import {FirebaseContext} from './../../firebase/';
import Swal from './Swal';
import * as CGeneral from './../../constantes/general/CGeneral';

const GrillaLugares = ({estacionamiento, cantidadLugares, lugares, posiciones}) => {
    const {firebase} = useContext(FirebaseContext);
    const [numeroLugar, setNumeroLugar] = useState(0);

    async function handleChangePosicion (e) {
        //si el numeroLugar es mayor o igual a la cantidad total de lugares, entonces se asignaron todos
        if (numeroLugar === cantidadLugares) {
            setNumeroLugar(0);
            await firebase.asignarPosiciones(estacionamiento, posiciones);
            Swal(CGeneral.OPERACION_COMPLETADA, 'Se han asignado todos los lugares');
        }
        else {
            const lugar = {
                ...lugares[numeroLugar],
                "posicion": e.currentTarget.name
            }
            posiciones.push(lugar);
            setNumeroLugar(numeroLugar +1);
            e.currentTarget.innerText = numeroLugar +1;
            e.currentTarget.disabled = true;
            }
        }
    return (
    <>
    <div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="1" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '1') ? lugares.find(lugar => lugar.posicion === '1').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="2" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '2') ? lugares.find(lugar => lugar.posicion === '2').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="3" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '3') ? lugares.find(lugar => lugar.posicion === '3').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="4" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '4') ? lugares.find(lugar => lugar.posicion === '4').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="5" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '5') ? lugares.find(lugar => lugar.posicion === '5').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="6" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '6') ? lugares.find(lugar => lugar.posicion === '6').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="7" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '7') ? lugares.find(lugar => lugar.posicion === '7').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="8" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '8') ? lugares.find(lugar => lugar.posicion === '8').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="9" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '9') ? lugares.find(lugar => lugar.posicion === '9').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="10" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '10') ? lugares.find(lugar => lugar.posicion === '10').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="11" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '11') ? lugares.find(lugar => lugar.posicion === '11').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="12" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '12') ? lugares.find(lugar => lugar.posicion === '12').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="13" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '13') ? lugares.find(lugar => lugar.posicion === '13').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="14" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '14') ? lugares.find(lugar => lugar.posicion === '14').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="15" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '15') ? lugares.find(lugar => lugar.posicion === '15').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="16" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '16') ? lugares.find(lugar => lugar.posicion === '16').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="17" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '17') ? lugares.find(lugar => lugar.posicion === '17').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="18" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '18') ? lugares.find(lugar => lugar.posicion === '18').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="19" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '19') ? lugares.find(lugar => lugar.posicion === '19').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="20" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '20') ? lugares.find(lugar => lugar.posicion === '20').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="21" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '21') ? lugares.find(lugar => lugar.posicion === '21').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="22" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '22') ? lugares.find(lugar => lugar.posicion === '22').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="23" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '23') ? lugares.find(lugar => lugar.posicion === '23').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="24" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '24') ? lugares.find(lugar => lugar.posicion === '24').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="25" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '25') ? lugares.find(lugar => lugar.posicion === '25').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="26" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '26') ? lugares.find(lugar => lugar.posicion === '26').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="27" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '27') ? lugares.find(lugar => lugar.posicion === '27').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="28" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '28') ? lugares.find(lugar => lugar.posicion === '28').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="29" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '29') ? lugares.find(lugar => lugar.posicion === '29').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="30" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '30') ? lugares.find(lugar => lugar.posicion === '30').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="31" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '31') ? lugares.find(lugar => lugar.posicion === '31').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="32" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '32') ? lugares.find(lugar => lugar.posicion === '32').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="33" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '33') ? lugares.find(lugar => lugar.posicion === '33').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="35" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '34') ? lugares.find(lugar => lugar.posicion === '34').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="35" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '35') ? lugares.find(lugar => lugar.posicion === '35').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="36" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '36') ? lugares.find(lugar => lugar.posicion === '36').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="37" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '37') ? lugares.find(lugar => lugar.posicion === '37').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="38" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '38') ? lugares.find(lugar => lugar.posicion === '38').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="39" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '39') ? lugares.find(lugar => lugar.posicion === '39').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="40" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '40') ? lugares.find(lugar => lugar.posicion === '40').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="41" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '41') ? lugares.find(lugar => lugar.posicion === '41').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="42" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '42') ? lugares.find(lugar => lugar.posicion === '42').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="43" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '43') ? lugares.find(lugar => lugar.posicion === '43').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="44" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '44') ? lugares.find(lugar => lugar.posicion === '44').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="45" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '45') ? lugares.find(lugar => lugar.posicion === '45').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="46" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '46') ? lugares.find(lugar => lugar.posicion === '46').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="47" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '47') ? lugares.find(lugar => lugar.posicion === '47').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="48" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '48') ? lugares.find(lugar => lugar.posicion === '48').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="49" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '49') ? lugares.find(lugar => lugar.posicion === '49').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="50" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '50') ? lugares.find(lugar => lugar.posicion === '50').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="51" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '51') ? lugares.find(lugar => lugar.posicion === '51').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="52" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '52') ? lugares.find(lugar => lugar.posicion === '52').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="53" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '53') ? lugares.find(lugar => lugar.posicion === '53').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="54" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '54') ? lugares.find(lugar => lugar.posicion === '54').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="55" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '55') ? lugares.find(lugar => lugar.posicion === '55').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="56" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '56') ? lugares.find(lugar => lugar.posicion === '56').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="57" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '57') ? lugares.find(lugar => lugar.posicion === '57').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="58" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '58') ? lugares.find(lugar => lugar.posicion === '58').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="59" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '59') ? lugares.find(lugar => lugar.posicion === '59').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="60" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '60') ? lugares.find(lugar => lugar.posicion === '60').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="61" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '61') ? lugares.find(lugar => lugar.posicion === '61').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="62" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '62') ? lugares.find(lugar => lugar.posicion === '62').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="63" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '63') ? lugares.find(lugar => lugar.posicion === '63').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="64" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '64') ? lugares.find(lugar => lugar.posicion === '64').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="65" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '65') ? lugares.find(lugar => lugar.posicion === '65').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="66" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '66') ? lugares.find(lugar => lugar.posicion === '66').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="67" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '67') ? lugares.find(lugar => lugar.posicion === '67').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="68" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '68') ? lugares.find(lugar => lugar.posicion === '68').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="69" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '69') ? lugares.find(lugar => lugar.posicion === '69').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="70" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '70') ? lugares.find(lugar => lugar.posicion === '70').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="71" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '71') ? lugares.find(lugar => lugar.posicion === '71').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="72" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '72') ? lugares.find(lugar => lugar.posicion === '72').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="73" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '73') ? lugares.find(lugar => lugar.posicion === '73').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="74" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '74') ? lugares.find(lugar => lugar.posicion === '74').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="75" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '75') ? lugares.find(lugar => lugar.posicion === '75').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="76" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '76') ? lugares.find(lugar => lugar.posicion === '76').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="77" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '77') ? lugares.find(lugar => lugar.posicion === '77').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="78" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '78') ? lugares.find(lugar => lugar.posicion === '78').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="79" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '79') ? lugares.find(lugar => lugar.posicion === '79').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="80" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '80') ? lugares.find(lugar => lugar.posicion === '80').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="81" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '81') ? lugares.find(lugar => lugar.posicion === '81').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="82" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '82') ? lugares.find(lugar => lugar.posicion === '82').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="83" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '83') ? lugares.find(lugar => lugar.posicion === '83').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="84" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '84') ? lugares.find(lugar => lugar.posicion === '84').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="85" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '85') ? lugares.find(lugar => lugar.posicion === '85').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="86" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '86') ? lugares.find(lugar => lugar.posicion === '86').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="87" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '87') ? lugares.find(lugar => lugar.posicion === '87').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="88" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '88') ? lugares.find(lugar => lugar.posicion === '88').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="89" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '89') ? lugares.find(lugar => lugar.posicion === '89').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="90" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '90') ? lugares.find(lugar => lugar.posicion === '90').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="91" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '91') ? lugares.find(lugar => lugar.posicion === '91').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="92" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '92') ? lugares.find(lugar => lugar.posicion === '92').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="93" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '93') ? lugares.find(lugar => lugar.posicion === '93').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="94" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '94') ? lugares.find(lugar => lugar.posicion === '94').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="95" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '95') ? lugares.find(lugar => lugar.posicion === '95').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="96" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '96') ? lugares.find(lugar => lugar.posicion === '96').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="97" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '97') ? lugares.find(lugar => lugar.posicion === '97').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="98" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '98') ? lugares.find(lugar => lugar.posicion === '98').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="99" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '99') ? lugares.find(lugar => lugar.posicion === '99').numero : ""}</button>
            <button style={{borderRadius: 5, margin: 5 , width: 30, height: 30, color: "#000000", borderColor: "#000000", border: 10, cursor: 'pointer'}} name="100" onClick={handleChangePosicion}>{lugares.find(lugar => lugar.posicion === '100') ? lugares.find(lugar => lugar.posicion === '100').numero : ""}</button>
        </div>
    </div>
    </>
    );
}
 
export default GrillaLugares;