export const SETEAR_PAGINA = 'SETEAR_PAGINA';

export const MOSTRAR_SPINNER = 'MOSTRAR_SPINNER';

export const OCULTAR_SPINNER = 'OCULTAR_SPINNER';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';

export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';