import React, {useState, useContext, useEffect} from 'react';
import {FirebaseContext} from './../../firebase/';
import { Typography } from '@material-ui/core';
import { useStyles } from './../reservas/Styles';

const GrillaLugaresReservar = ({estacionamiento, cantidadLugares, lugares, posiciones}) => {
    const classes = useStyles();
    const [lugar, setLugar] = useState(0);
    const handleChangeLugar = (e) => {
        setLugar(e.currentTarget.innerText);
        localStorage.setItem('lugar', lugar);
    }
    return (
    <>
    <div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '1') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '1') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="1" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '1') ? lugares.find(lugar => lugar.posicion === '1').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '2') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '2') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="2" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '2') ? lugares.find(lugar => lugar.posicion === '2').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '3') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '3') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="3" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '3') ? lugares.find(lugar => lugar.posicion === '3').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '4') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '4') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="4" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '4') ? lugares.find(lugar => lugar.posicion === '4').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '5') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '5') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="5" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '5') ? lugares.find(lugar => lugar.posicion === '5').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '6') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '6') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="6" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '6') ? lugares.find(lugar => lugar.posicion === '6').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '7') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '7') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="7" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '7') ? lugares.find(lugar => lugar.posicion === '7').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '8') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '8') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="8" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '8') ? lugares.find(lugar => lugar.posicion === '8').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '9') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '9') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="9" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '9') ? lugares.find(lugar => lugar.posicion === '9').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '10') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '10') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="10" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '10') ? lugares.find(lugar => lugar.posicion === '10').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '11') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '11') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="11" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '11') ? lugares.find(lugar => lugar.posicion === '11').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '12') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '12') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="12" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '12') ? lugares.find(lugar => lugar.posicion === '12').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '13') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '13') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="13" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '13') ? lugares.find(lugar => lugar.posicion === '13').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '14') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '14') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="14" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '14') ? lugares.find(lugar => lugar.posicion === '14').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '15') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '15') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="15" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '15') ? lugares.find(lugar => lugar.posicion === '15').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '16') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '16') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="16" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '16') ? lugares.find(lugar => lugar.posicion === '16').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '17') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '17') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="17" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '17') ? lugares.find(lugar => lugar.posicion === '17').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '18') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '18') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="18" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '18') ? lugares.find(lugar => lugar.posicion === '18').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '19') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '19') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="19" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '19') ? lugares.find(lugar => lugar.posicion === '19').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '20') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '20') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="20" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '20') ? lugares.find(lugar => lugar.posicion === '20').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '21') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '21') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="21" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '21') ? lugares.find(lugar => lugar.posicion === '21').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '22') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '22') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="22" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '22') ? lugares.find(lugar => lugar.posicion === '22').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '23') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '23') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="23" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '23') ? lugares.find(lugar => lugar.posicion === '23').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '24') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '24') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="24" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '24') ? lugares.find(lugar => lugar.posicion === '24').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '25') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '25') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="25" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '25') ? lugares.find(lugar => lugar.posicion === '25').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '26') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '26') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="26" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '26') ? lugares.find(lugar => lugar.posicion === '26').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '27') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '27') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="27" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '27') ? lugares.find(lugar => lugar.posicion === '27').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '28') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '28') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="28" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '28') ? lugares.find(lugar => lugar.posicion === '28').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '29') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '29') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="29" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '29') ? lugares.find(lugar => lugar.posicion === '29').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '30') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '30') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="30" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '30') ? lugares.find(lugar => lugar.posicion === '30').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '31') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '31') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="31" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '31') ? lugares.find(lugar => lugar.posicion === '31').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '32') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '32') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="32" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '32') ? lugares.find(lugar => lugar.posicion === '32').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '33') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '33') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="33" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '33') ? lugares.find(lugar => lugar.posicion === '33').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '34') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '34') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="35" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '34') ? lugares.find(lugar => lugar.posicion === '34').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '35') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '35') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="35" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '35') ? lugares.find(lugar => lugar.posicion === '35').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '36') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '36') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="36" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '36') ? lugares.find(lugar => lugar.posicion === '36').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '37') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '37') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="37" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '37') ? lugares.find(lugar => lugar.posicion === '37').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '38') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '38') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="38" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '38') ? lugares.find(lugar => lugar.posicion === '38').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '39') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '39') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="39" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '39') ? lugares.find(lugar => lugar.posicion === '39').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '40') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '40') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="40" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '40') ? lugares.find(lugar => lugar.posicion === '40').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '41') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '41') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="41" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '41') ? lugares.find(lugar => lugar.posicion === '41').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '42') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '42') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="42" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '42') ? lugares.find(lugar => lugar.posicion === '42').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '43') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '43') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="43" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '43') ? lugares.find(lugar => lugar.posicion === '43').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '44') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '44') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="44" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '44') ? lugares.find(lugar => lugar.posicion === '44').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '45') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '45') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="45" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '45') ? lugares.find(lugar => lugar.posicion === '45').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '46') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '46') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="46" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '46') ? lugares.find(lugar => lugar.posicion === '46').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '47') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '47') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="47" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '47') ? lugares.find(lugar => lugar.posicion === '47').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '48') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '48') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="48" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '48') ? lugares.find(lugar => lugar.posicion === '48').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '49') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '49') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="49" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '49') ? lugares.find(lugar => lugar.posicion === '49').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '50') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '50') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="50" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '50') ? lugares.find(lugar => lugar.posicion === '50').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '51') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '51') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="51" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '51') ? lugares.find(lugar => lugar.posicion === '51').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '52') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '52') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="52" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '52') ? lugares.find(lugar => lugar.posicion === '52').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '53') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '53') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="53" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '53') ? lugares.find(lugar => lugar.posicion === '53').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '54') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '54') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="54" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '54') ? lugares.find(lugar => lugar.posicion === '54').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '55') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '55') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="55" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '55') ? lugares.find(lugar => lugar.posicion === '55').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '56') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '56') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="56" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '56') ? lugares.find(lugar => lugar.posicion === '56').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '57') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '57') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="57" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '57') ? lugares.find(lugar => lugar.posicion === '57').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '58') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '58') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="58" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '58') ? lugares.find(lugar => lugar.posicion === '58').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '59') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '59') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="59" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '59') ? lugares.find(lugar => lugar.posicion === '59').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '60') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '60') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="60" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '60') ? lugares.find(lugar => lugar.posicion === '60').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '61') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '61') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="61" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '61') ? lugares.find(lugar => lugar.posicion === '61').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '62') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '62') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="62" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '62') ? lugares.find(lugar => lugar.posicion === '62').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '63') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '63') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="63" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '63') ? lugares.find(lugar => lugar.posicion === '63').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '64') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '64') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="64" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '64') ? lugares.find(lugar => lugar.posicion === '64').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '65') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '65') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="65" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '65') ? lugares.find(lugar => lugar.posicion === '65').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '66') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '66') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="66" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '66') ? lugares.find(lugar => lugar.posicion === '66').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '67') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '67') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="67" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '67') ? lugares.find(lugar => lugar.posicion === '67').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '68') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '68') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="68" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '68') ? lugares.find(lugar => lugar.posicion === '68').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '69') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '69') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="69" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '69') ? lugares.find(lugar => lugar.posicion === '69').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '70') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '70') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="70" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '70') ? lugares.find(lugar => lugar.posicion === '70').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '71') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '71') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="71" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '71') ? lugares.find(lugar => lugar.posicion === '71').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '72') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '72') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="72" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '72') ? lugares.find(lugar => lugar.posicion === '72').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '73') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '73') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="73" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '73') ? lugares.find(lugar => lugar.posicion === '73').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '74') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '74') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="74" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '74') ? lugares.find(lugar => lugar.posicion === '74').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '75') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '75') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="75" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '75') ? lugares.find(lugar => lugar.posicion === '75').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '76') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '76') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="76" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '76') ? lugares.find(lugar => lugar.posicion === '76').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '77') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '77') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="77" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '77') ? lugares.find(lugar => lugar.posicion === '77').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '78') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '78') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="78" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '78') ? lugares.find(lugar => lugar.posicion === '78').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '79') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '79') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="79" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '79') ? lugares.find(lugar => lugar.posicion === '79').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '80') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '80') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="80" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '80') ? lugares.find(lugar => lugar.posicion === '80').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '81') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '81') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="81" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '81') ? lugares.find(lugar => lugar.posicion === '81').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '82') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '82') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="82" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '82') ? lugares.find(lugar => lugar.posicion === '82').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '83') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '83') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="83" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '83') ? lugares.find(lugar => lugar.posicion === '83').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '84') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '84') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="84" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '84') ? lugares.find(lugar => lugar.posicion === '84').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '85') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '85') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="85" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '85') ? lugares.find(lugar => lugar.posicion === '85').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '86') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '86') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="86" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '86') ? lugares.find(lugar => lugar.posicion === '86').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '87') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '87') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="87" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '87') ? lugares.find(lugar => lugar.posicion === '87').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '88') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '88') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="88" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '88') ? lugares.find(lugar => lugar.posicion === '88').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '89') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '89') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="89" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '89') ? lugares.find(lugar => lugar.posicion === '89').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '90') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '90') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="90" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '90') ? lugares.find(lugar => lugar.posicion === '90').numero : ""}</button>
        </div>
        <div style={{justifyContent: 'center', display: 'flex'}}>
            <button disabled={lugares.find(lugar => lugar.posicion === '91') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '91') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="91" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '91') ? lugares.find(lugar => lugar.posicion === '91').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '92') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '92') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="92" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '92') ? lugares.find(lugar => lugar.posicion === '92').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '93') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '93') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="93" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '93') ? lugares.find(lugar => lugar.posicion === '93').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '94') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '94') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="94" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '94') ? lugares.find(lugar => lugar.posicion === '94').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '95') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '95') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="95" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '95') ? lugares.find(lugar => lugar.posicion === '95').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '96') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '96') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="96" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '96') ? lugares.find(lugar => lugar.posicion === '96').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '97') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '97') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="97" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '97') ? lugares.find(lugar => lugar.posicion === '97').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '98') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '98') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="98" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '98') ? lugares.find(lugar => lugar.posicion === '98').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '99') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '99') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="99" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '99') ? lugares.find(lugar => lugar.posicion === '99').numero : ""}</button>
            <button disabled={lugares.find(lugar => lugar.posicion === '100') ? false : true} style={{borderRadius: 5, margin: 5 , width: 30, height: 30, backgroundColor: lugares.find(lugar => lugar.posicion === '100') ? '#4db6ac' : "#FFFFFF", color: "#FFFFFF", borderColor: "#FFFFFF", border: 10, cursor: 'pointer'}} name="100" onClick={handleChangeLugar}>{lugares.find(lugar => lugar.posicion === '100') ? lugares.find(lugar => lugar.posicion === '100').numero : ""}</button>
        </div>
    <Typography className={classes.subtitulos}>Lugar seleccionado: {localStorage.getItem('lugar') ? localStorage.getItem('lugar'): '-'}</Typography>
    </div>
    </>
    );
}
 
export default GrillaLugaresReservar;